In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Dataa.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Fahmi' 30.0 850000.0]
 ['Raka' nan 730000.0]
 ['Julius' 15.0 290000.0]
 ['Raka' 44.0 120000.0]
 ['Julius' 51.0 nan]
 ['Fahmi' 49.0 670000.0]
 ['Raka' 67.0 880000.0]
 ['Fahmi' 48.0 420000.0]
 ['Julius' nan 570000.0]
 ['Fahmi' 37.0 250000.0]
 ['Raka' nan 660000.0]
 ['Raka' 19.0 nan]
 ['Julius' 38.0 710000.0]
 ['Fahmi' 60.0 330000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Fahmi' 30.0 850000.0]
 ['Raka' 41.63636363636363 730000.0]
 ['Julius' 15.0 290000.0]
 ['Raka' 44.0 120000.0]
 ['Julius' 51.0 540000.0]
 ['Fahmi' 49.0 670000.0]
 ['Raka' 67.0 880000.0]
 ['Fahmi' 48.0 420000.0]
 ['Julius' 41.63636363636363 570000.0]
 ['Fahmi' 37.0 250000.0]
 ['Raka' 41.63636363636363 660000.0]
 ['Raka' 19.0 540000.0]
 ['Julius' 38.0 710000.0]
 ['Fahmi' 60.0 330000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 30.0 850000.0]
 [0.0 0.0 1.0 41.63636363636363 730000.0]
 [0.0 1.0 0.0 15.0 290000.0]
 [0.0 0.0 1.0 44.0 120000.0]
 [0.0 1.0 0.0 51.0 540000.0]
 [1.0 0.0 0.0 49.0 670000.0]
 [0.0 0.0 1.0 67.0 880000.0]
 [1.0 0.0 0.0 48.0 420000.0]
 [0.0 1.0 0.0 41.63636363636363 570000.0]
 [1.0 0.0 0.0 37.0 250000.0]
 [0.0 0.0 1.0 41.63636363636363 660000.0]
 [0.0 0.0 1.0 19.0 540000.0]
 [0.0 1.0 0.0 38.0 710000.0]
 [1.0 0.0 0.0 60.0 330000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 1.0 0.0 15.0 290000.0]
 [0.0 0.0 1.0 41.63636363636363 660000.0]
 [0.0 1.0 0.0 51.0 540000.0]
 [0.0 0.0 1.0 41.63636363636363 730000.0]
 [0.0 1.0 0.0 38.0 710000.0]
 [1.0 0.0 0.0 30.0 850000.0]
 [1.0 0.0 0.0 60.0 330000.0]
 [1.0 0.0 0.0 37.0 250000.0]
 [0.0 1.0 0.0 41.63636363636363 570000.0]
 [0.0 0.0 1.0 19.0 540000.0]
 [1.0 0.0 0.0 49.0 670000.0]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 44.0 120000.0]
 [1.0 0.0 0.0 48.0 420000.0]
 [0.0 0.0 1.0 67.0 880000.0]]


In [14]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 1]


In [15]:
print(y_test)

[0 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 1.0 0.0 -1.8578801597238739 -1.442202280797687]
 [0.0 0.0 1.0 0.24462958563779916 0.5475479845740368]
 [0.0 1.0 0.0 0.983737107044804 -0.0977764258167926]
 [0.0 0.0 1.0 0.24462958563779916 0.9239872239686873]
 [0.0 1.0 0.0 -0.042402461510551874 0.8164331555702157]
 [1.0 0.0 0.0 -0.6738729652369247 1.5693116343595166]
 [1.0 0.0 0.0 1.6941414237369734 -1.227094144000744]
 [1.0 0.0 0.0 -0.12133627447634848 -1.6573104175946303]
 [0.0 1.0 0.0 0.24462958563779916 0.06355467678091473]
 [0.0 0.0 1.0 -1.5421449078606873 -0.0977764258167926]
 [1.0 0.0 0.0 0.8258694811132108 0.6013250187732725]]


In [18]:
print(x_test)

[[0.0 0.0 1.0 0.4312004162842277 -2.3564118621846952]
 [1.0 0.0 0.0 0.7469356681474142 -0.743100836207622]
 [0.0 0.0 1.0 2.24667811449755 1.730642736957224]]
